// <auto-generated />
namespace Pharmacy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class EntitiesMedicineStockMedicineSalesPurchaseShelf : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EntitiesMedicineStockMedicineSalesPurchaseShelf));
        
        string IMigrationMetadata.Id
        {
            get { return "202206012019518_Entities Medicine StockMedicine Sales Purchase Shelf"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
