// <auto-generated />
namespace Pharmacy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class correctrelationshipfrommedicinetostock : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(correctrelationshipfrommedicinetostock));
        
        string IMigrationMetadata.Id
        {
            get { return "202206030759442_correct relationship from medicine to stock"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
