// <auto-generated />
namespace Pharmacy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Salescs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Salescs));
        
        string IMigrationMetadata.Id
        {
            get { return "202206022106204_Sales.cs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
