// <auto-generated />
namespace Pharmacy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class newfieldminQuantityforsendingnotification : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newfieldminQuantityforsendingnotification));
        
        string IMigrationMetadata.Id
        {
            get { return "202206031540170_new field minQuantity for sending notification"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
